name: runTests
on:  
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Deno
        uses: denolib/setup-deno@v2
      
      - name: Run Tests
        run: deno test --allow-run